# Generated by Django 5.0.6 on 2024-10-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='room',
        ),
    ]
