# Generated by Django 5.0.6 on 2024-10-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], default='Lecture', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'class_assigned', 'type')},
        ),
    ]
