# Generated by Django 5.0.6 on 2024-10-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_timeslot_day_remove_timeslot_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticAlgorithmParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.IntegerField(default=50)),
                ('mutation_rate', models.FloatField(default=0.01)),
                ('generations', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('timeslot', models.CharField(max_length=20)),
                ('is_lab', models.BooleanField(default=False)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.courseassignment')),
            ],
            options={
                'ordering': ['day', 'timeslot'],
                'unique_together': {('day', 'room', 'timeslot')},
            },
        ),
    ]
