# Generated by Django 5.0.6 on 2024-10-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_geneticalgorithmparams_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTimeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.shift')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneticAlgorithmParams',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
