# Generated by Django 5.0.6 on 2024-11-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
        ('timetable', '0002_alter_courseassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('students', models.ManyToManyField(limit_choices_to=3, to='student_management.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
            ],
        ),
    ]
